package Transport

enum class TransportType {
    GET_USER,
    GET_USER_CHATS,
    GET_USER_CONTACTS,
    REMOVE_USER,
    EDIT_USER,
    ADD_CONTACT,
    REMOVE_CONTACT,

    SEND_MESSAGE,
    EDIT_MESSAGE,
    DELETE_MESSAGE,
    GET_MESSAGE,

    ADD_CHAT,
    GET_CHAT,
    GET_MESSAGES,
    GET_MEMBERS,
    GET_ADMINS,
    DELETE_CHAT,
    EDIT_CHAT,
    ADD_MEMBER,
    KICK_MEMBER,
    ADD_ADMIN,
    REMOVE_ADMIN,

    REGISTER,
    LOGIN
}