enum class TransportType {
    SEND_MESSAGE, GET_USER, GET_CHAT, GET_MESSAGES, REGISTER, LOGIN, DELETE_CHAT, DELETE_MESSAGE, EDIT_MESSAGE,
    EDIT_USER, GET_USER_CHATS, ADD_CHAT, REMOVE_USER, EDIT_CHAT, ADD_MEMBER, ADD_ADMIN
}
